### ISSUE TITLE
 throw new Exception("Expected 4 salt.");

### ISSUE THREAD

**Issue by KlausFuhrer** [Doublevil/SigmarsBoredom#1]
![image](https://user-images.githubusercontent.com/98599327/151563782-f1594bb9-1933-453a-8b20-064ff0ae0dd5.png)

Hello :)

I am totally new to this with coding and also Visual studios. What is going on here? I press start and it looks like its working until the Salt error occure.

**Comment by Doublevil** [comment]
Hi there!
Looks like the board reader didn't find 4 salt tiles. As this is the first check, I'm inclined to think that it didn't read anything on the board properly.
In Visual Studio, you can set breakpoints to stop the execution on a certain line of code, and then execute the code instruction by instruction to see exactly what is happening. It's pretty hard to explain if you're a beginner though, so let's set this aside for the moment.

Did you make sure you were running the game on the Sigmar's Garden board screen, in borderless window mode, at a resolution of 1920x1080?

Another thing to check, before throwing this exception, it should perform the "search" phase, i.e. highlight each tile type by clicking in the game window. Does it do that?

**Comment by KlausFuhrer** [comment]
Hey
I ran it as it should, 1920x1080 windowed and got it to somewhat work by deleting the line "throw new Exception("Expected x xxx.")" on all of them.
Didnt know if that would do anything, but it actually did! 
It worked smooth until around round 50 ish, then it got stuck on "trying to solve puzzle..". Had to restart it many times and would't always work after a restart - a bit unstable. 
But hey, cant complain! Your awesome work helped me save alot of time and brain cells! :D

Thanks agian!!
